version: '3'

services:
  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8989:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''